apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-hub
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: default
  source:
    path: ./workflows/
    repoURL: https://github.com/codefresh-io/argo-hub.git
    targetRevision: HEAD
  destination:
    name: in-cluster
    namespace: gitops
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
      allowEmpty: false
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=false
      - ApplyOutOfSyncOnly=false
      - ServerSideApply=true
      - RespectIgnoreDifferences=false
