apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: codefresh
spec:
  template:
    serviceAccountName: argo-server
  eventBusName: codefresh-eventbus
  dependencies:
    - name: github-81b9289c-755f-440a-9abe-158d952d4e09
      eventName: github-81b9289c-755f-440a-9abe-158d952d4e09
      eventSourceName: codefresh
      filters:
        data:
          - path: body.X-GitHub-Event
            value:
              - push
            type: string
          - path: body.ref
            template: '{{ (split "/" .Input)._1 }}'
            value:
              - heads
            type: string
  triggers:
    - template:
        name: hello-world
        conditions: github-81b9289c-755f-440a-9abe-158d952d4e09
        argoWorkflow:
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: WorkflowTemplate
              metadata:
                generateName: codefresh-hello-world-
              spec:
                workflowTemplateRef:
                  name: template-hello-world
          parameters: []
