apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: codefresh
spec:
  eventBusName: codefresh-eventbus
  service:
    ports:
      - port: 80
  template:
    serviceAccountName: argo-server
  github:
    github-81b9289c-755f-440a-9abe-158d952d4e09:
      events:
        - push
      repositories:
        - owner: maryiaCodefresh
          names:
            - word-mastermind
      webhook:
        port: '80'
        method: POST
        endpoint: /webhooks/gitops/codefresh/github-81b9289c-755f-440a-9abe-158d952d4e09
        url: https://651bd573a935bf255bb155c2-cf.tunnels.cf-cd.com
      active: true
      insecure: false
      contentType: json
      deleteHookOnFinish: true
      apiToken:
        name: runtime-repo-creds-secret
        key: password
