apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pastr-production
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: default
  source:
    path: kustomize/overlays/prod
    repoURL: https://github.com/maryiaCodefresh/pastr.git
    targetRevision: HEAD
  destination:
    name: in-cluster
    namespace: production
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
      allowEmpty: false
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false
      - ServerSideApply=true
      - RespectIgnoreDifferences=false
