apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: sensor-cf-ci
spec:
  template:
    serviceAccountName: argo-server
  eventBusName: codefresh-eventbus
  dependencies:
    - name: github-f50d76a9-c450-466d-8d63-984c95bae7f2
      eventName: github-f50d76a9-c450-466d-8d63-984c95bae7f2
      eventSourceName: sensor-cf-ci
      filters:
        data:
          - path: body.X-GitHub-Event
            value:
              - push
            type: string
          - path: body.ref
            template: '{{ (split "/" .Input)._1 }}'
            value:
              - heads
            type: string
  triggers:
    - template:
        name: push-cf-ci
        conditions: github-f50d76a9-c450-466d-8d63-984c95bae7f2
        argoWorkflow:
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: WorkflowTemplate
              metadata:
                generateName: sensor-cf-ci-push-cf-ci-
              spec:
                arguments:
                  parameters:
                    - name: GITHUB_REPO
                      value: ''
                    - name: MANIFEST_PATH
                      value: ''
                    - name: GIT_REPO_URL
                      value: ''
                    - name: IMAGE_NAME
                      value: ''
                    - name: IMAGE_TAG
                      value: ''
                    - name: GIT_REVISION
                      value: ''
                    - name: GIT_BRANCH
                      value: ''
                    - name: GIT_COMMIT_URL
                      value: ''
                    - name: GIT_COMMIT_MESSAGE
                      value: ''
                    - name: GIT_TOKEN_SECRET
                      value: ''
                    - name: REGISTRY_CREDS_SECRET
                      value: ''
                    - name: DOCKER_CONFIG_SECRET
                      value: ''
                workflowTemplateRef:
                  name: argo-hub.ci-simple.0.0.1
          parameters:
            - dest: spec.arguments.parameters.0.value
              src:
                dependencyName: github-f50d76a9-c450-466d-8d63-984c95bae7f2
                dataTemplate: '{{ .Input.body.repository.name }}'
            - dest: spec.arguments.parameters.1.value
              src:
                dependencyName: github-f50d76a9-c450-466d-8d63-984c95bae7f2
                dataTemplate: ./manifests/word-mastermind.yml
            - dest: spec.arguments.parameters.2.value
              src:
                dependencyName: github-f50d76a9-c450-466d-8d63-984c95bae7f2
                dataTemplate: https://github.com/maryiaCodefresh/word-mastermind.git
            - dest: spec.arguments.parameters.3.value
              src:
                dependencyName: github-f50d76a9-c450-466d-8d63-984c95bae7f2
                dataTemplate: mashabrauer/word-mastermind
            - dest: spec.arguments.parameters.4.value
              src:
                dependencyName: github-f50d76a9-c450-466d-8d63-984c95bae7f2
                dataTemplate: '4.0'
            - dest: spec.arguments.parameters.5.value
              src:
                dependencyName: github-f50d76a9-c450-466d-8d63-984c95bae7f2
                dataTemplate: '{{ trunc 7 .Input.body.after }}'
            - dest: spec.arguments.parameters.6.value
              src:
                dependencyName: github-f50d76a9-c450-466d-8d63-984c95bae7f2
                dataTemplate: '{{ trimPrefix "refs/heads/" .Input.body.ref }}'
            - dest: spec.arguments.parameters.7.value
              src:
                dependencyName: github-f50d76a9-c450-466d-8d63-984c95bae7f2
                dataTemplate: '{{ .Input.body.head_commit.url }}'
            - dest: spec.arguments.parameters.8.value
              src:
                dependencyName: github-f50d76a9-c450-466d-8d63-984c95bae7f2
                dataTemplate: '{{ .Input.body.head_commit.message }}'
            - dest: spec.arguments.parameters.9.value
              src:
                dependencyName: github-f50d76a9-c450-466d-8d63-984c95bae7f2
                dataTemplate: github-token
            - dest: spec.arguments.parameters.10.value
              src:
                dependencyName: github-f50d76a9-c450-466d-8d63-984c95bae7f2
                dataTemplate: registry-creds
            - dest: spec.arguments.parameters.11.value
              src:
                dependencyName: github-f50d76a9-c450-466d-8d63-984c95bae7f2
                dataTemplate: docker-config
