apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: sensor-cf-ci
spec:
  eventBusName: codefresh-eventbus
  service:
    ports:
      - port: 80
  template:
    serviceAccountName: argo-server
  github:
    github-f50d76a9-c450-466d-8d63-984c95bae7f2:
      events:
        - push
      repositories:
        - owner: maryiaCodefresh
          names:
            - word-mastermind
      webhook:
        port: '80'
        method: POST
        endpoint: >-
          /webhooks/gitops/sensor-cf-ci/github-f50d76a9-c450-466d-8d63-984c95bae7f2
        url: https://651bd573a935bf255bb155c2-cf.tunnels.cf-cd.com
      active: true
      insecure: false
      contentType: json
      deleteHookOnFinish: true
      apiToken:
        name: runtime-repo-creds-secret
        key: password
