apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: template-hello-world
spec:
  entrypoint: whalesay
  templates:
    - name: whalesay
      container:
        image: docker/whalesay
        command: [cowsay]
        args: ["hello world"]
        resources:
            limits:
                memory: 32Mi
                cpu: 100m