apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: update-image
spec:
  entrypoint: update-image
  templates:
    - name: update-image
      inputs:
        parameters:
        - name: GITHUB_REPO
        - name: MANIFEST_PATH
        - name: IMAGE_TAG
      script:
        name: step
        image: alpine/git
        command: [sh]
        source: |
          git clone https://github.com/{{ inputs.parameters.GITHUB_REPO }} /workspace/repo
          cd /workspace/repo
          git checkout -b update-image
          sed -i "s/image:.*\$/image: your-container-image:{{ inputs.parameters.IMAGE_TAG }}/" {{ inputs.parameters.MANIFEST_PATH }}
          git add .
          git commit -m "Update container image tag to {{ inputs.parameters.IMAGE_TAG }}"
          git push origin update-image