apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: update-image
spec:
  entrypoint: update-image
  templates:
    - name: update-image
      inputs:
        parameters:
          - name: REPO
          - name: REVISION
          - name: GIT_TOKEN_SECRET
          - name: GITHUB_REPO
          - name: MANIFEST_PATH
          - name: IMAGE_TAG
          - name: USER
          - name: EMAIL
          - name: IMAGE_NAME
      script:
        image: alpine/git
        env:
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: '{{ inputs.parameters.GIT_TOKEN_SECRET }}'
                  key: token
        command: ["sh"]
        source: |
          mkdir gitrepo 
          git clone --depth=1 https://{{ inputs.parameters.USER }}:$TOKEN@github.com/{{ inputs.parameters.GITHUB_REPO }}.git gitrepo
          cd gitrepo/
          sed -i "s#image:.*#image: {{ inputs.parameters.IMAGE_NAME }}:{{ inputs.parameters.IMAGE_TAG }}#g" {{ inputs.parameters.MANIFEST_PATH }}
          cat {{ inputs.parameters.MANIFEST_PATH }}
          git config user.name {{ inputs.parameters.USER }}
          git config user.email {{ inputs.parameters.EMAIL }}
          git add .
          git commit -m "Update container image tag to {{ inputs.parameters.IMAGE_TAG }}"
          git push -u origin master