apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: update-image
spec:
  entrypoint: update-image
  templates:
    - name: update-image
      inputs:
        artifacts:
          - name: repo
            path: /tmp/repo
            git:
              repo: '{{ inputs.parameters.REPO }}'
              revision: '{{ inputs.parameters.REVISION }}'
              usernameSecret:
                name: '{{ inputs.parameters.GIT_TOKEN_SECRET }}'
                key: token
        parameters:
          - name: REPO
          - name: REVISION
          - name: GIT_TOKEN_SECRET
          - name: GITHUB_REPO
          - name: MANIFEST_PATH
          - name: IMAGE_TAG
          - name: USER
          - name: EMAIL
          - name: IMAGE_NAME
      script:
        image: alpine/git
        workingDir: '{{ inputs.artifacts.repo.path }}'
        command: ["sh"]
        source: |
          cat {{ workflow.parameters.GIT_TOKEN_SECRET }}
          git clone https://github.com/{{ inputs.parameters.GITHUB_REPO }}  /workspace/repo
          cd /workspace/repo
          sed -i "s#image:.*#image: {{ inputs.parameters.IMAGE_NAME }}:{{ inputs.parameters.IMAGE_TAG }}#g" {{ inputs.parameters.MANIFEST_PATH }}
          cat {{ inputs.parameters.MANIFEST_PATH }}
          git config user.name {{ inputs.parameters.USER }}
          git config user.email {{ inputs.parameters.EMAIL }}
          git add .
          git commit -m "Update container image tag to {{ inputs.parameters.IMAGE_TAG }}"
          git remote set-url origin https://{{ inputs.parameters.USER }}@github.com/{{ inputs.parameters.GITHUB_REPO }}.git
          git push -u origin master